apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    name: frontend-pod
    app: guestbook-app
spec:
  containers:
    - name: frontend-app
      image: gcr.io/google-samples/gb-frontend:v4
